# Generated by Django 2.0.2 on 2018-03-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffs', '0004_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college_name',
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, choices=[('u', 'Umass Amherst'), ('a', 'Amherst College'), ('s', 'Smith College'), ('m', 'Mount Holyoke College'), ('h', 'Hamshire College')], default='u', help_text='college choice', max_length=1),
        ),
    ]
