# Generated by Django 2.0.2 on 2018-07-20 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ffs', '0009_auto_20180412_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('password', models.CharField(blank=True, help_text='Enter a password', max_length=120)),
                ('college', models.CharField(blank=True, choices=[('u', 'Umass Amherst'), ('a', 'Amherst College'), ('s', 'Smith College'), ('m', 'Mount Holyoke College'), ('h', 'Hampshire College')], default='u', help_text='college choice', max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('star_count', models.DecimalField(decimal_places=0, max_digits=1)),
                ('image', models.FileField(blank=True, null=True, upload_to='user_profile_picture/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AlterField(
            model_name='flag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ffs.Student'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ffs.Student'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='student',
            name='django_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
