# Generated by Django 2.0.2 on 2018-03-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffs', '0005_auto_20180323_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('s', 'Sold')], default='a', help_text='Item availability', max_length=1),
        ),
    ]
