# Generated by Django 2.0.2 on 2018-03-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffs', '0006_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, help_text='Enter a password', max_length=120),
        ),
    ]
